# -*- coding: utf-8 -*-
"""Guessing Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17YsZaiUD5AHoRmhHU7Xq3Ex-a3lIzuyd
"""

name = "sajan"
def display():
  global name
  name = name + " Kumar"
print(name)
display()
print(name)

import numpy as np
import random
def sajan(a):
  game_level = input("Enter the level you want to play, hard or easy")
  if game_level == "hard":
    for i in range(5):

      guess = int(input("Enter your guess to predict the number: "))
      if guess == a:
        print(f"You got it right in {i+1} attempts")
        break
      elif guess > a:
        print(f"Your attempt is {i+1}/5, Your guess is too high, please try again")

      elif guess < a:
        print(f" Your attempt is {i+1}/5, Your guess is too low, ")

    else:
        print("You are out of attempts")

  elif game_level == "easy":
    for i in range(10):

      guess = int(input("Enter your guess to predict the number: "))
      if guess == a:
        print(f"You got it right in {i+1} attempts")
        break
      elif guess > a:
        print(f"Your attempt is {i+1}/10, Your guess is too high, please try again")

      elif guess < a:
        print(f" Your attempt is {i+1}/10, Your guess is too low, ")
    else:
        print("You are out of attempts")



n = random.randint(1,100)
sajan(n)



import numpy as np
import random

def play_game_hard(a):
    for i in range(5):
        guess = int(input("Enter your guess to predict the number: "))
        if guess == a:
            print(f"You got it right in {i+1} attempts")
            return
        elif guess > a:
            print(f"Your attempt is {i+1}/5, Your guess is too high, please try again")
        elif guess < a:
            print(f"Your attempt is {i+1}/5, Your guess is too low, please try again")
    print("You are out of attempts")

def play_game_easy(a):
    for i in range(10):
        guess = int(input("Enter your guess to predict the number: "))
        if guess == a:
            print(f"You got it right in {i+1} attempts")
            return
        elif guess > a:
            print(f"Your attempt is {i+1}/10, Your guess is too high, please try again")
        elif guess < a:
            print(f"Your attempt is {i+1}/10, Your guess is too low, please try again")
    print("You are out of attempts")

def sajan(a):
    game_level = input("Enter the level you want to play, hard or easy: ")
    if game_level == "hard":
        play_game_hard(a)
    elif game_level == "easy":
        play_game_easy(a)

n = random.randint(1, 100)
sajan(n)

